changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
    - title: WeChat Runtime
      labels:
        - wechat
        - runtime
    - title: Documentation
      labels:
        - docs
    - title: Tests and CI
      labels:
        - tests
        - ci
    - title: Other Changes
      labels:
        - "*"
